
const ALERT_GET_LIST_DATA_PROCESSING = 'ALERT_GET_LIST_DATA_PROCESSING'
const ALERT_GET_LIST_DATA_SUCCESS = 'ALERT_GET_LIST_DATA_SUCCESS'
const ALERT_GET_LIST_DATA_UNREAD_SUCCESS = 'ALERT_GET_LIST_DATA_UNREAD_SUCCESS'
const ALERT_GET_LIST_DATA_FAIL = 'ALERT_GET_LIST_DATA_FAIL'

const ALERT_UPDATE_NOTIFY_PROCESSING = 'ALERT_UPDATE_NOTIFY_PROCESSING'
const ALERT_UPDATE_NOTIFY_SUCCESS = 'ALERT_UPDATE_NOTIFY_SUCCESS'
const ALERT_UPDATE_NOTIFY_FAIL = 'ALERT_UPDATE_NOTIFY_FAIL'

const ALERT_GET_TYPE_ALL = 'all'
const ALERT_GET_TYPE_UNREAD = 'unread'

export {
    ALERT_GET_LIST_DATA_PROCESSING,
    ALERT_GET_LIST_DATA_SUCCESS,
    ALERT_GET_LIST_DATA_UNREAD_SUCCESS,
    ALERT_GET_LIST_DATA_FAIL,

    ALERT_UPDATE_NOTIFY_PROCESSING,
    ALERT_UPDATE_NOTIFY_SUCCESS,
    ALERT_UPDATE_NOTIFY_FAIL,

    ALERT_GET_TYPE_ALL,
    ALERT_GET_TYPE_UNREAD,
}
