const DEVICE_GET_DATA_PROCESSING = 'DEVICE_GET_DATA_PROCESSING'
const DEVICE_GET_DATA_SUCCESS = 'DEVICE_GET_DATA_SUCCESS'
const DEVICE_GET_DATA_FAIL = 'DEVICE_GET_DATA_FAIL'

const DEVICE_ADD_DATA_PROCESSING = 'DEVICE_ADD_DATA_PROCESSING'
const DEVICE_ADD_DATA_SUCCESS = 'DEVICE_ADD_DATA_SUCCESS'
const DEVICE_ADD_DATA_FAIL = 'DEVICE_ADD_DATA_FAIL'

export {
    DEVICE_GET_DATA_PROCESSING,
    DEVICE_GET_DATA_SUCCESS,
    DEVICE_GET_DATA_FAIL,

    DEVICE_ADD_DATA_PROCESSING,
    DEVICE_ADD_DATA_SUCCESS,
    DEVICE_ADD_DATA_FAIL,

}
