const GASDATA_GET_DATA_PROCESSING = 'GASDATA_GET_DATA_PROCESSING'
const GASDATA_GET_DATA_SUCCESS = 'GASDATA_GET_DATA_SUCCESS'
const GASDATA_GET_DATA_FAIL = 'GASDATA_GET_DATA_FAIL'

const STATUS = {
    ACTIVE: 'active',
    INACTIVE: 'inactive',
}

export {
    GASDATA_GET_DATA_PROCESSING,
    GASDATA_GET_DATA_SUCCESS,
    GASDATA_GET_DATA_FAIL,

    STATUS,
}
