const GASLEAK_GET_DATA_PROCESSING = 'GASLEAK_GET_DATA_PROCESSING'
const GASLEAK_GET_DATA_SUCCESS = 'GASLEAK_GET_DATA_SUCCESS'
const GASLEAK_GET_DATA_FAIL = 'GASLEAK_GET_DATA_FAIL'

export {
    GASLEAK_GET_DATA_PROCESSING,
    GASLEAK_GET_DATA_SUCCESS,
    GASLEAK_GET_DATA_FAIL,
}
