
const NOTIFICATION_GET_LIST_DATA_PROCESSING = 'NOTIFICATION_GET_LIST_DATA_PROCESSING'
const NOTIFICATION_GET_LIST_DATA_SUCCESS = 'NOTIFICATION_GET_LIST_DATA_SUCCESS'
const NOTIFICATION_GET_LIST_DATA_FAIL = 'NOTIFICATION_GET_LIST_DATA_FAIL'

export {
    NOTIFICATION_GET_LIST_DATA_PROCESSING,
    NOTIFICATION_GET_LIST_DATA_SUCCESS,
    NOTIFICATION_GET_LIST_DATA_FAIL,
}
