
const NOTIFICATION_GET_LIST_DATA_PROCESSING = 'NOTIFICATION_GET_LIST_DATA_PROCESSING'
const NOTIFICATION_GET_LIST_DATA_SUCCESS = 'NOTIFICATION_GET_LIST_DATA_SUCCESS'
const NOTIFICATION_GET_LIST_DATA_UNREAD_SUCCESS = 'NOTIFICATION_GET_LIST_DATA_UNREAD_SUCCESS'
const NOTIFICATION_GET_LIST_DATA_FAIL = 'NOTIFICATION_GET_LIST_DATA_FAIL'

const NOTIFICATION_UPDATE_NOTIFY_PROCESSING = 'NOTIFICATION_UPDATE_NOTIFY_PROCESSING'
const NOTIFICATION_UPDATE_NOTIFY_SUCCESS = 'NOTIFICATION_UPDATE_NOTIFY_SUCCESS'
const NOTIFICATION_UPDATE_NOTIFY_FAIL = 'NOTIFICATION_UPDATE_NOTIFY_FAIL'

const NOTIFICATION_GET_TYPE_ALL = 'all'
const NOTIFICATION_GET_TYPE_UNREAD = 'unread'

export {
    NOTIFICATION_GET_LIST_DATA_PROCESSING,
    NOTIFICATION_GET_LIST_DATA_SUCCESS,
    NOTIFICATION_GET_LIST_DATA_UNREAD_SUCCESS,
    NOTIFICATION_GET_LIST_DATA_FAIL,

    NOTIFICATION_UPDATE_NOTIFY_PROCESSING,
    NOTIFICATION_UPDATE_NOTIFY_SUCCESS,
    NOTIFICATION_UPDATE_NOTIFY_FAIL,

    NOTIFICATION_GET_TYPE_ALL,
    NOTIFICATION_GET_TYPE_UNREAD,
}
