const SETTING_GET_DATA_PROCESSING = 'SETTING_GET_DATA_PROCESSING'
const SETTING_GET_DATA_SUCCESS = 'SETTING_GET_DATA_SUCCESS'
const SETTING_GET_DATA_FAIL = 'SETTING_GET_DATA_FAIL'

export {
    SETTING_GET_DATA_PROCESSING,
    SETTING_GET_DATA_SUCCESS,
    SETTING_GET_DATA_FAIL,

}
