
const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS'
const USER_AUTH_PROCESSING = 'USER_AUTH_PROCESSING'
const USER_AUTH_FAIL = 'USER_AUTH_FAIL'

const USER_AUTH_SIGN_OUT_SUCCESS = 'USER_AUTH_SIGN_OUT_SUCCESS'
const USER_AUTH_SIGN_OUT_PROCESSING = 'USER_AUTH_SIGN_OUT_PROCESSING'
const USER_AUTH_SIGN_OUT_FAIL = 'USER_AUTH_SIGN_OUT_FAIL'

const USER_REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS'
const USER_REQUEST_PROCESSING = 'USER_REQUEST_PROCESSING'
const USER_REQUEST_FAIL = 'USER_REQUEST_FAIL'

const USER_REGISTER_REQUEST_SUCCESS = 'USER_REGISTER_REQUEST_SUCCESS'
const USER_REGISTER_REQUEST_PROCESSING = 'USER_REGISTER_REQUEST_PROCESSING'
const USER_REGISTER_REQUEST_FAIL = 'USER_REGISTER_REQUEST_FAIL'

export {
    USER_AUTH_SUCCESS,
    USER_AUTH_PROCESSING,
    USER_AUTH_FAIL,

    USER_AUTH_SIGN_OUT_SUCCESS,
    USER_AUTH_SIGN_OUT_PROCESSING,
    USER_AUTH_SIGN_OUT_FAIL,

    USER_REQUEST_SUCCESS,
    USER_REQUEST_PROCESSING,
    USER_REQUEST_FAIL,

    USER_REGISTER_REQUEST_SUCCESS,
    USER_REGISTER_REQUEST_PROCESSING,
    USER_REGISTER_REQUEST_FAIL,
}
